#ifndef SEIZA_CABI_H
#define SEIZA_CABI_H

/* Generated by cbindgen from the seiza-cabi crate. Do not edit by hand; run `cargo build -p seiza-cabi` to regenerate. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 * Memory ownership and lifetimes
 * ==============================
 * Everything this library returns is allocated by Rust. Release it ONLY with
 * the matching seiza_*_free function below -- never with free(), delete,
 * CoTaskMemFree, Marshal.FreeHGlobal, or any other allocator. Mixing allocators
 * is undefined behavior. Every free function accepts NULL and no-ops, so it is
 * always safe to call.
 *
 * OWNED by the caller (you must release it):
 *   - SeizaRenderedImage* returned by the seiza_rendered_image_open* functions
 *       -> release with seiza_rendered_image_free().
 *   - SeizaRenderedImage16* returned by the seiza_rendered_image16_open*
 *     functions -> release with seiza_rendered_image16_free().
 *   - SeizaBackgroundModel* returned by seiza_background_fit
 *       -> release with seiza_background_model_free().
 *   - SeizaLiveStacker* returned by seiza_live_stacker_create / _open_fits
 *       -> release with seiza_live_stacker_free(), or consume with
 *          seiza_live_stacker_finish().
 *   - SeizaStackSnapshot* returned by seiza_live_stacker_snapshot / _finish
 *       -> release with seiza_stack_snapshot_free().
 *   - char* returned by seiza_catalog_status_json, seiza_solve_image_json, and
 *     seiza_live_stacker_push_*_json, plus any char* stored into an `error_out`
 *     argument on failure
 *       -> release with seiza_string_free().
 *
 * BORROWED by the caller (do NOT free; valid only while the owner is alive):
 *   - const uint8_t* from seiza_rendered_image_rgba / _bgra and const char*
 *     from seiza_rendered_image_metadata_json point INTO the SeizaRenderedImage
 *     and dangle the moment it is freed. Copy them out before freeing the image
 *     if you need them to outlive it.
 *   - const uint16_t* from seiza_rendered_image16_rgba and const char* from
 *     seiza_rendered_image16_metadata_json point INTO the SeizaRenderedImage16
 *     and dangle the moment it is freed.
 *   - const char* from seiza_background_model_diagnostics_json points INTO the
 *     SeizaBackgroundModel and dangles when the model is freed.
 *   - const float* / uint32_t* from seiza_live_stacker_* point INTO live stack
 *     state and remain valid only until its next mutable call, finish, or free.
 *   - const float* / uint32_t* from seiza_stack_snapshot_* point INTO the
 *     immutable SeizaStackSnapshot and dangle when the snapshot is freed.
 *   - const char* from seiza_core_version is static and is never freed.
 *   - the `json` argument to a SeizaCatalogSetupProgressCallback is valid only
 *     for the duration of that one callback; copy it if you need it afterward.
 *
 * Convention: a non-const `char*` return transfers ownership (free it); a
 * `const` return is borrowed (do not free).
 *
 * Errors: functions taking `char** error_out` set *error_out to NULL on success
 * and to an OWNED message on failure (and return NULL / false). Free that
 * message with seiza_string_free().
 *
 * Threading: externally synchronize each live stacker and do not mutate,
 * finish, or free it while another thread reads a borrowed live view. Do not
 * free any opaque owner while another thread uses it or its borrowed pointers.
 * Do not free the same pointer twice or use a pointer after its owner is freed.
 */

/*
 Additive background subtraction mode for
 [`seiza_background_model_correct_in_place`].
 */
#define SEIZA_BACKGROUND_CORRECTION_SUBTRACT 0

/*
 Multiplicative background division mode for
 [`seiza_background_model_correct_in_place`].
 */
#define SEIZA_BACKGROUND_CORRECTION_DIVIDE 1

/*
 An opaque fitted background model. Release it with
 [`seiza_background_model_free`]. Its diagnostics string is borrowed and
 remains valid until the model is freed.
 */
typedef struct SeizaBackgroundModel SeizaBackgroundModel;

/*
 An opaque incremental stacker. Release it with
 [`seiza_live_stacker_free`], or consume it with
 [`seiza_live_stacker_finish`].
 */
typedef struct SeizaLiveStacker SeizaLiveStacker;

/*
 An opaque, owned rendered image. C sees only a pointer; release it with
 [`seiza_rendered_image_free`]. Not `repr(C)`: it is only ever handed to C as
 an opaque pointer, so its layout is private (and cbindgen forward-declares
 it).
 */
typedef struct SeizaRenderedImage SeizaRenderedImage;

/*
 An opaque, owned 16-bit rendered image. Its RGBA samples are native-endian
 `u16` values suitable for a high-bit-depth image encoder. C sees only a
 pointer; release it with [`seiza_rendered_image16_free`].
 */
typedef struct SeizaRenderedImage16 SeizaRenderedImage16;

/*
 An immutable owned stack result. Its image and count pointers are borrowed
 until [`seiza_stack_snapshot_free`] is called.
 */
typedef struct SeizaStackSnapshot SeizaStackSnapshot;

typedef void (*SeizaCatalogSetupProgressCallback)(const char*, void*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

const char *seiza_core_version(void);

/*
 Applies damped Richardson-Lucy deconvolution to interleaved linear `float`
 samples in place. `channels` must be one or three and `data_length` must
 equal `width * height * channels`. RGB samples are pixel-interleaved.
 The operation is synchronous, retains no pointer after returning, and leaves
 the input unchanged when validation or restoration fails.

 # Safety
 `data` must point to `data_length` writable floats. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
bool seiza_deconvolve_in_place(float *data,
                               size_t data_length,
                               size_t width,
                               size_t height,
                               size_t channels,
                               float psf_fwhm_pixels,
                               size_t iterations,
                               float amount,
                               float noise_fraction,
                               float max_correction,
                               char **error_out);

/*
 Fits a compact background model to interleaved linear `float` samples.

 `channels` must be one or three and `data_length` must equal
 `width * height * channels`. RGB samples are pixel-interleaved. Pass null
 `mask` with zero `mask_length` for automatic fitting, or `width * height`
 bytes where `1` excludes a pixel. The fitted model owns its compact data and
 does not borrow either input buffer after this call returns.
 Pass null or empty `config_json` for `BackgroundConfig::default()`; otherwise
 provide a serialized `seiza-background` `BackgroundConfig`.

 # Safety
 `data` must point to `data_length` readable floats. A non-null `mask` must
 point to `mask_length` readable bytes containing only zero or one. A
 non-null `config_json` must be NUL-terminated. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaBackgroundModel *seiza_background_fit(const float *data,
                                           size_t data_length,
                                           size_t width,
                                           size_t height,
                                           size_t channels,
                                           const uint8_t *mask,
                                           size_t mask_length,
                                           const char *config_json,
                                           char **error_out);

/*
 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
size_t seiza_background_model_width(const SeizaBackgroundModel *model);

/*
 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
size_t seiza_background_model_height(const SeizaBackgroundModel *model);

/*
 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
size_t seiza_background_model_channels(const SeizaBackgroundModel *model);

/*
 Returns the number of floats required by render and correction buffers.

 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
size_t seiza_background_model_data_length(const SeizaBackgroundModel *model);

/*
 Returns borrowed fitted coefficients, references, samples, and diagnostics
 as JSON. The string remains valid until the model is freed.

 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
const char *seiza_background_model_diagnostics_json(const SeizaBackgroundModel *model);

/*
 Renders a fitted background into a caller-owned interleaved float buffer.

 # Safety
 `model` must be a live pointer returned by [`seiza_background_fit`].
 `output` must point to `output_length` writable floats. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
bool seiza_background_model_render(const SeizaBackgroundModel *model,
                                   float *output,
                                   size_t output_length,
                                   char **error_out);

/*
 Corrects an interleaved linear float buffer in place. Use
 `SEIZA_BACKGROUND_CORRECTION_SUBTRACT` for additive subtraction or
 `SEIZA_BACKGROUND_CORRECTION_DIVIDE` for multiplicative division.

 # Safety
 `model` must be a live pointer returned by [`seiza_background_fit`]. `data`
 must point to `data_length` writable floats. When non-null, `error_out` must
 point to writable storage for one pointer.
 */
bool seiza_background_model_correct_in_place(const SeizaBackgroundModel *model,
                                             float *data,
                                             size_t data_length,
                                             uint32_t mode,
                                             char **error_out);

/*
 # Safety
 `model` must be null or a pointer returned by [`seiza_background_fit`] that
 has not already been freed.
 */
void seiza_background_model_free(SeizaBackgroundModel *model);

/*
 Creates an incremental stack from a copied linear mono or interleaved RGB
 reference frame. Array frames are assumed to be calibrated and debayered.
 Pass null or empty `options_json` for `StackOptions::default()`.

 # Safety
 `reference` must point to `reference_length` readable floats. A non-null
 `options_json` must be NUL-terminated. When non-null, `error_out` must point
 to writable storage for one pointer.
 */
SeizaLiveStacker *seiza_live_stacker_create(const float *reference,
                                            size_t reference_length,
                                            size_t width,
                                            size_t height,
                                            size_t channels,
                                            const char *options_json,
                                            char **error_out);

/*
 Opens a FITS or XISF reference and optional integrated bias, dark, and flat
 masters. A positive `dark_exposure_seconds` overrides the dark metadata; zero
 uses the metadata. Pass null or empty `options_json` for defaults. All files
 are fully read during this call and are not kept open afterward.

 # Safety
 `reference_path` must be a valid NUL-terminated string. Optional paths and
 `options_json` may be null; when non-null they must be NUL-terminated. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
SeizaLiveStacker *seiza_live_stacker_open_fits(const char *reference_path,
                                               const char *bias_path,
                                               const char *dark_path,
                                               const char *flat_path,
                                               double dark_exposure_seconds,
                                               const char *options_json,
                                               char **error_out);

/*
 Registers and offers one copied, calibrated linear frame to the stack.
 Returns owned disposition JSON for both accepted and rejected frames; free
 it with [`seiza_string_free`]. A rejected frame is a successful call and is
 represented by `accepted: false` rather than `error_out`.

 # Safety
 `stacker` must be a live pointer returned by a `seiza_live_stacker_*`
 constructor. `frame` must point to `frame_length` readable floats. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
char *seiza_live_stacker_push_linear_json(SeizaLiveStacker *stacker,
                                          const float *frame,
                                          size_t frame_length,
                                          size_t width,
                                          size_t height,
                                          size_t channels,
                                          char **error_out);

/*
 Opens, calibrates, registers, and offers one FITS or XISF frame to the stack. The
 returned disposition JSON is owned and must be freed with
 [`seiza_string_free`]. Each source path may be offered only once.

 # Safety
 `stacker` must be a live pointer returned by a `seiza_live_stacker_*`
 constructor. `path` must be a valid NUL-terminated string. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
char *seiza_live_stacker_push_fits_json(SeizaLiveStacker *stacker,
                                        const char *path,
                                        char **error_out);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
size_t seiza_live_stacker_width(const SeizaLiveStacker *stacker);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
size_t seiza_live_stacker_height(const SeizaLiveStacker *stacker);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
size_t seiza_live_stacker_channels(const SeizaLiveStacker *stacker);

/*
 Returns the sample count for every live-view and snapshot buffer.

 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
size_t seiza_live_stacker_data_length(const SeizaLiveStacker *stacker);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
uint32_t seiza_live_stacker_accepted_frames(const SeizaLiveStacker *stacker);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
uint32_t seiza_live_stacker_rejected_frames(const SeizaLiveStacker *stacker);

/*
 Borrows the current interleaved linear mean without copying it. Zero-
 coverage samples are undefined. The pointer remains valid only until the
 next mutable stacker operation or the stacker is freed/finished.

 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
const float *seiza_live_stacker_mean(const SeizaLiveStacker *stacker);

/*
 Borrows the accepted-observation count for each image sample. The pointer
 has the same lifetime as [`seiza_live_stacker_mean`].

 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
const uint32_t *seiza_live_stacker_coverage(const SeizaLiveStacker *stacker);

/*
 Borrows the rejected-observation count for each image sample. The pointer
 has the same lifetime as [`seiza_live_stacker_mean`].

 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
const uint32_t *seiza_live_stacker_rejected_samples(const SeizaLiveStacker *stacker);

/*
 Copies the current mean, variance, coverage, and rejection maps into an
 immutable owned snapshot. Prefer the borrowed live view for display-only
 updates and [`seiza_live_stacker_finish`] for copy-free finalization.

 # Safety
 `stacker` must be a live `SeizaLiveStacker` pointer. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaStackSnapshot *seiza_live_stacker_snapshot(const SeizaLiveStacker *stacker, char **error_out);

/*
 Consumes a live stacker and moves its full-frame state into an immutable
 snapshot without cloning it. Once a non-null live handle is accepted,
 `*stacker` is set to null and consumed even if finalization reports an
 error.

 # Safety
 `stacker` must point to writable storage containing null or a live pointer
 returned by a `seiza_live_stacker_*` constructor. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaStackSnapshot *seiza_live_stacker_finish(SeizaLiveStacker **stacker, char **error_out);

/*
 # Safety
 `stacker` must be null or a live pointer returned by a
 `seiza_live_stacker_*` constructor and must not already be finished/freed.
 */
void seiza_live_stacker_free(SeizaLiveStacker *stacker);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
size_t seiza_stack_snapshot_width(const SeizaStackSnapshot *snapshot);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
size_t seiza_stack_snapshot_height(const SeizaStackSnapshot *snapshot);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
size_t seiza_stack_snapshot_channels(const SeizaStackSnapshot *snapshot);

/*
 Returns the sample count for every snapshot buffer.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
size_t seiza_stack_snapshot_data_length(const SeizaStackSnapshot *snapshot);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
uint32_t seiza_stack_snapshot_accepted_frames(const SeizaStackSnapshot *snapshot);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
uint32_t seiza_stack_snapshot_rejected_frames(const SeizaStackSnapshot *snapshot);

/*
 Borrows the immutable interleaved linear mean until the snapshot is freed.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
const float *seiza_stack_snapshot_image(const SeizaStackSnapshot *snapshot);

/*
 Borrows the immutable per-sample variance until the snapshot is freed.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
const float *seiza_stack_snapshot_variance(const SeizaStackSnapshot *snapshot);

/*
 Borrows the immutable per-sample accepted count until the snapshot is freed.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
const uint32_t *seiza_stack_snapshot_coverage(const SeizaStackSnapshot *snapshot);

/*
 Borrows the immutable per-sample rejection count until the snapshot is
 freed.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
const uint32_t *seiza_stack_snapshot_rejected_samples(const SeizaStackSnapshot *snapshot);

/*
 Writes the immutable stack as an unstretched 32-bit floating-point FITS,
 preserving compatible reference headers.

 # Safety
 `snapshot` must be a live `SeizaStackSnapshot` pointer. `path` must be a
 valid NUL-terminated string. When non-null, `error_out` must point to
 writable storage for one pointer.
 */
bool seiza_stack_snapshot_write_fits(const SeizaStackSnapshot *snapshot,
                                     const char *path,
                                     char **error_out);

/*
 # Safety
 `snapshot` must be null or a live pointer returned by a snapshot/finalize
 function and must not already be freed.
 */
void seiza_stack_snapshot_free(SeizaStackSnapshot *snapshot);

/*
 Returns catalog readiness and resolved component paths as JSON.

 # Safety
 `catalog_directory` may be null or a valid NUL-terminated string. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
char *seiza_catalog_status_json(const char *catalog_directory, char **error_out);

/*
 Downloads and installs a solver-ready Seiza catalog preset.

 Preset `0` is the standard G≤17 blind-solving package, `1` is the optional
 G≤20 package, and `2` installs every published catalog. The call is
 synchronous and must run off the UI thread. Progress JSON is valid only for
 the duration of each callback.

 # Safety
 `catalog_directory` may be null or a valid NUL-terminated string. `context`
 is passed through untouched to `progress`. When non-null, `error_out` must
 point to writable storage for one pointer.
 */
bool seiza_catalog_setup(const char *catalog_directory,
                         uint32_t preset,
                         SeizaCatalogSetupProgressCallback progress,
                         void *context,
                         char **error_out);

/*
 Opens and renders an image for the C ABI.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open(const char *path,
                                              double target_median,
                                              double shadows_clip,
                                              uint32_t max_dimension,
                                              char **error_out);

/*
 Opens and renders an image with an explicit RGB stretch mode.

 Mode `0` is per-channel auto, `1` is linked auto, and `2` is linear.
 Non-RGB FITS/XISF and standard raster images ignore this setting.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open_with_rgb_stretch(const char *path,
                                                               double target_median,
                                                               double shadows_clip,
                                                               uint32_t max_dimension,
                                                               uint32_t rgb_stretch_mode,
                                                               char **error_out);

/*
 Opens a FITS or XISF image and renders it with parameterized processing described by
 `config_json`. The value may be one serialized `seiza-stretch`
 `StretchConfig` (the original schema), a non-empty array of configs, or an
 object with `stretch`, optional `background`, optional `deconvolution`, and
 optional `interactive_preview` fields. Array stages are applied in order
 using `f32` intermediates and converted to RGBA only after the final stage.
 Background correction and deconvolution, when requested, are applied to
 linear samples in that order before the first stretch stage. Interactive
 preview mode bounds the linear samples to `max_dimension` before processing
 and reuses the source/background-prepared pixels across stretch and
 deconvolution edits; full renders should leave it false.

 # Safety
 `path` and `config_json` must be valid NUL-terminated strings. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open_with_stretch_config(const char *path,
                                                                  const char *config_json,
                                                                  uint32_t max_dimension,
                                                                  char **error_out);

/*
 Opens and renders an image to native-endian RGBA16 for high-bit-depth
 export. This is a separate allocation from the RGBA8 preview API, so normal
 preview renders do not pay the memory cost of both pixel formats.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage16 *seiza_rendered_image16_open(const char *path,
                                                  double target_median,
                                                  double shadows_clip,
                                                  uint32_t max_dimension,
                                                  char **error_out);

/*
 Opens and renders an image to native-endian RGBA16 with an explicit RGB
 stretch mode. Mode `0` is per-channel auto, `1` is linked auto, and `2` is
 linear. Non-RGB FITS/XISF and standard raster images ignore this setting.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage16 *seiza_rendered_image16_open_with_rgb_stretch(const char *path,
                                                                   double target_median,
                                                                   double shadows_clip,
                                                                   uint32_t max_dimension,
                                                                   uint32_t rgb_stretch_mode,
                                                                   char **error_out);

/*
 Opens a FITS or XISF image and renders its parameterized processing stack to
 native-endian RGBA16. The JSON schema and processing order are identical to
 [`seiza_rendered_image_open_with_stretch_config`], but the final stretch is
 quantized directly from `f32` to `u16` instead of passing through RGBA8.

 # Safety
 `path` and `config_json` must be valid NUL-terminated strings. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaRenderedImage16 *seiza_rendered_image16_open_with_stretch_config(const char *path,
                                                                      const char *config_json,
                                                                      uint32_t max_dimension,
                                                                      char **error_out);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
uint32_t seiza_rendered_image_width(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
uint32_t seiza_rendered_image_height(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`]. The returned buffer is valid until the image
 is freed.
 */
const uint8_t *seiza_rendered_image_rgba(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
size_t seiza_rendered_image_rgba_length(const SeizaRenderedImage *image);

/*
 Returns the image as BGRA8 (Direct2D / WinUI byte order), computed from the
 canonical RGBA on first use and cached. The returned buffer is valid until
 the image is freed.

 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
const uint8_t *seiza_rendered_image_bgra(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
size_t seiza_rendered_image_bgra_length(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`]. The returned string is valid until the image
 is freed.
 */
const char *seiza_rendered_image_metadata_json(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a pointer returned by [`seiza_rendered_image_open`]
 that has not already been freed.
 */
void seiza_rendered_image_free(SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
uint32_t seiza_rendered_image16_width(const SeizaRenderedImage16 *image);

/*
 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
uint32_t seiza_rendered_image16_height(const SeizaRenderedImage16 *image);

/*
 Returns borrowed native-endian RGBA16 samples. The returned buffer remains
 valid until the image is freed.

 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
const uint16_t *seiza_rendered_image16_rgba(const SeizaRenderedImage16 *image);

/*
 Returns the RGBA16 buffer length in `uint16_t` elements, not bytes.

 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
size_t seiza_rendered_image16_rgba_length(const SeizaRenderedImage16 *image);

/*
 Returns borrowed render metadata JSON. The string remains valid until the
 image is freed.

 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
const char *seiza_rendered_image16_metadata_json(const SeizaRenderedImage16 *image);

/*
 # Safety
 `image` must be null or a pointer returned by a
 `seiza_rendered_image16_open*` function that has not already been freed.
 */
void seiza_rendered_image16_free(SeizaRenderedImage16 *image);

/*
 Solves an image and returns a JSON string for the C ABI.

 # Safety
 `path` must be a valid NUL-terminated string. `catalog_directory` may be
 null or a valid NUL-terminated string. When non-null, `error_out` must point
 to writable storage for one pointer.
 */
char *seiza_solve_image_json(const char *path,
                             const char *catalog_directory,
                             double minimum_scale_arcsec_per_pixel,
                             double maximum_scale_arcsec_per_pixel,
                             uint8_t sip_order,
                             char **error_out);

/*
 # Safety
 `value` must be null or a string returned by this library that has not
 already been freed.
 */
void seiza_string_free(char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SEIZA_CABI_H */
