#ifndef SEIZA_CABI_H
#define SEIZA_CABI_H

/* Generated by cbindgen from the seiza-cabi crate. Do not edit by hand; run `cargo build -p seiza-cabi` to regenerate. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 * Memory ownership and lifetimes
 * ==============================
 * Everything this library returns is allocated by Rust. Release it ONLY with
 * the matching seiza_*_free function below -- never with free(), delete,
 * CoTaskMemFree, Marshal.FreeHGlobal, or any other allocator. Mixing allocators
 * is undefined behavior. Every free function accepts NULL and no-ops, so it is
 * always safe to call.
 *
 * OWNED by the caller (you must release it):
 *   - SeizaRenderedImage* returned by the seiza_rendered_image_open* functions
 *       -> release with seiza_rendered_image_free().
 *   - char* returned by seiza_catalog_status_json and seiza_solve_image_json,
 *     and any char* stored into an `error_out` argument on failure
 *       -> release with seiza_string_free().
 *
 * BORROWED by the caller (do NOT free; valid only while the owner is alive):
 *   - const uint8_t* from seiza_rendered_image_rgba / _bgra and const char*
 *     from seiza_rendered_image_metadata_json point INTO the SeizaRenderedImage
 *     and dangle the moment it is freed. Copy them out before freeing the image
 *     if you need them to outlive it.
 *   - const char* from seiza_core_version is static and is never freed.
 *   - the `json` argument to a SeizaCatalogSetupProgressCallback is valid only
 *     for the duration of that one callback; copy it if you need it afterward.
 *
 * Convention: a non-const `char*` return transfers ownership (free it); a
 * `const` return is borrowed (do not free).
 *
 * Errors: functions taking `char** error_out` set *error_out to NULL on success
 * and to an OWNED message on failure (and return NULL / false). Free that
 * message with seiza_string_free().
 *
 * Threading: do not free a SeizaRenderedImage while another thread is still
 * reading its borrowed pointers. Do not free the same pointer twice, and do not
 * use a pointer after freeing its owner.
 */

/*
 An opaque, owned rendered image. C sees only a pointer; release it with
 [`seiza_rendered_image_free`]. Not `repr(C)`: it is only ever handed to C as
 an opaque pointer, so its layout is private (and cbindgen forward-declares
 it).
 */
typedef struct SeizaRenderedImage SeizaRenderedImage;

typedef void (*SeizaCatalogSetupProgressCallback)(const char*, void*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

const char *seiza_core_version(void);

/*
 Returns catalog readiness and resolved component paths as JSON.

 # Safety
 `catalog_directory` may be null or a valid NUL-terminated string. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
char *seiza_catalog_status_json(const char *catalog_directory, char **error_out);

/*
 Downloads and installs a solver-ready Seiza catalog preset.

 Preset `0` is the standard G≤17 blind-solving package, `1` is the optional
 G≤20 package, and `2` installs every published catalog. The call is
 synchronous and must run off the UI thread. Progress JSON is valid only for
 the duration of each callback.

 # Safety
 `catalog_directory` may be null or a valid NUL-terminated string. `context`
 is passed through untouched to `progress`. When non-null, `error_out` must
 point to writable storage for one pointer.
 */
bool seiza_catalog_setup(const char *catalog_directory,
                         uint32_t preset,
                         SeizaCatalogSetupProgressCallback progress,
                         void *context,
                         char **error_out);

/*
 Opens and renders an image for the C ABI.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open(const char *path,
                                              double target_median,
                                              double shadows_clip,
                                              uint32_t max_dimension,
                                              char **error_out);

/*
 Opens and renders an image with an explicit RGB stretch mode.

 Mode `0` is per-channel auto, `1` is linked auto, and `2` is linear.
 Non-RGB FITS and standard raster images ignore this setting.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open_with_rgb_stretch(const char *path,
                                                               double target_median,
                                                               double shadows_clip,
                                                               uint32_t max_dimension,
                                                               uint32_t rgb_stretch_mode,
                                                               char **error_out);

/*
 Opens a FITS image and renders it with a parameterized stretch described by
 `config_json` — a serialized `seiza-stretch` `StretchConfig` (the same schema
 the `seiza stretch` tooling uses), giving access to the full GHS/MTF/params
 pipeline without further ABI additions.

 # Safety
 `path` and `config_json` must be valid NUL-terminated strings. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open_with_stretch_config(const char *path,
                                                                  const char *config_json,
                                                                  uint32_t max_dimension,
                                                                  char **error_out);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
uint32_t seiza_rendered_image_width(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
uint32_t seiza_rendered_image_height(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`]. The returned buffer is valid until the image
 is freed.
 */
const uint8_t *seiza_rendered_image_rgba(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
size_t seiza_rendered_image_rgba_length(const SeizaRenderedImage *image);

/*
 Returns the image as BGRA8 (Direct2D / WinUI byte order), computed from the
 canonical RGBA on first use and cached. The returned buffer is valid until
 the image is freed.

 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
const uint8_t *seiza_rendered_image_bgra(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
size_t seiza_rendered_image_bgra_length(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`]. The returned string is valid until the image
 is freed.
 */
const char *seiza_rendered_image_metadata_json(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a pointer returned by [`seiza_rendered_image_open`]
 that has not already been freed.
 */
void seiza_rendered_image_free(SeizaRenderedImage *image);

/*
 Solves an image and returns a JSON string for the C ABI.

 # Safety
 `path` must be a valid NUL-terminated string. `catalog_directory` may be
 null or a valid NUL-terminated string. When non-null, `error_out` must point
 to writable storage for one pointer.
 */
char *seiza_solve_image_json(const char *path,
                             const char *catalog_directory,
                             double minimum_scale_arcsec_per_pixel,
                             double maximum_scale_arcsec_per_pixel,
                             uint8_t sip_order,
                             char **error_out);

/*
 # Safety
 `value` must be null or a string returned by this library that has not
 already been freed.
 */
void seiza_string_free(char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SEIZA_CABI_H */
