#ifndef SEIZA_CABI_H
#define SEIZA_CABI_H

/* Generated by cbindgen from the seiza-cabi crate. Do not edit by hand; run `cargo build -p seiza-cabi` to regenerate. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 * Memory ownership and lifetimes
 * ==============================
 * Everything this library returns is allocated by Rust. Release it ONLY with
 * the matching seiza_*_free function below -- never with free(), delete,
 * CoTaskMemFree, Marshal.FreeHGlobal, or any other allocator. Mixing allocators
 * is undefined behavior. Every free function accepts NULL and no-ops, so it is
 * always safe to call.
 *
 * OWNED by the caller (you must release it):
 *   - SeizaRenderedImage* returned by the seiza_rendered_image_open* functions
 *     or seiza_live_stacker_render_preview
 *       -> release with seiza_rendered_image_free().
 *   - SeizaRenderedImage16* returned by the seiza_rendered_image16_open*
 *     functions -> release with seiza_rendered_image16_free().
 *   - SeizaBackgroundModel* returned by seiza_background_fit
 *       -> release with seiza_background_model_free().
 *   - SeizaLiveStacker* returned by seiza_live_stacker_create / _open_fits /
 *     _open_context
 *       -> release with seiza_live_stacker_free(), or consume with
 *          seiza_live_stacker_finish().
 *   - SeizaCancelSignal* returned by seiza_cancel_signal_create
 *       -> release with seiza_cancel_signal_free() after all borrowing work
 *          has returned.
 *   - SeizaStackSnapshot* returned by seiza_live_stacker_snapshot / _finish
 *       -> release with seiza_stack_snapshot_free().
 *   - SeizaStackExportSnapshot* returned by
 *     seiza_live_stacker_export_snapshot
 *       -> release with seiza_stack_export_snapshot_free().
 *   - char* returned by seiza_catalog_status_json, seiza_solve_image_json,
 *     seiza_probe_frame_json, seiza_calibration_plan_json,
 *     seiza_calibration_build_master_json, seiza_live_stacker_state_json, and
 *     seiza_live_stacker_push_*_json, plus any char* stored into an
 *     `error_out` argument on failure
 *       -> release with seiza_string_free().
 *
 * BORROWED by the caller (do NOT free; valid only while the owner is alive):
 *   - const uint8_t* from seiza_rendered_image_rgba / _bgra and const char*
 *     from seiza_rendered_image_metadata_json point INTO the SeizaRenderedImage
 *     and dangle the moment it is freed. Copy them out before freeing the image
 *     if you need them to outlive it.
 *   - const uint16_t* from seiza_rendered_image16_rgba and const char* from
 *     seiza_rendered_image16_metadata_json point INTO the SeizaRenderedImage16
 *     and dangle the moment it is freed.
 *   - const char* from seiza_background_model_diagnostics_json points INTO the
 *     SeizaBackgroundModel and dangles when the model is freed.
 *   - const float* / uint32_t* from seiza_live_stacker_* point INTO live stack
 *     state and remain valid only until its next mutable call, finish, or free.
 *   - const float* / uint32_t* from seiza_stack_snapshot_* point INTO the
 *     immutable SeizaStackSnapshot and dangle when the snapshot is freed.
 *   - const char* from seiza_core_version is static and is never freed.
 *   - the `json` argument to a SeizaCatalogSetupProgressCallback is valid only
 *     for the duration of that one callback; copy it if you need it afterward.
 *
 * Convention: a non-const `char*` return transfers ownership (free it); a
 * `const` return is borrowed (do not free).
 *
 * Errors: functions taking `char** error_out` set *error_out to NULL on success
 * and to an OWNED message on failure (and return NULL / false). Free that
 * message with seiza_string_free().
 *
 * Threading: externally synchronize each live stacker and do not mutate,
 * finish, or free it while another thread reads a borrowed live view. Do not
 * free any opaque owner while another thread uses it or its borrowed pointers.
 * A SeizaStackExportSnapshot is independent of its live stacker and may be
 * transferred to an output worker after capture; do not free it until every
 * write using it has returned.
 * seiza_cancel_signal_cancel is the exception: it is thread-safe and is meant
 * to be called while a worker borrows the signal, but the owner still must not
 * be freed until that worker returns.
 * Do not free the same pointer twice or use a pointer after its owner is freed.
 */

/*
 Additive background subtraction mode for
 [`seiza_background_model_correct_in_place`].
 */
#define SEIZA_BACKGROUND_CORRECTION_SUBTRACT 0

/*
 Multiplicative background division mode for
 [`seiza_background_model_correct_in_place`].
 */
#define SEIZA_BACKGROUND_CORRECTION_DIVIDE 1

/*
 The most channels a measurement reports separately: mono or debayered RGB.
 */
#define SEIZA_SNR_MAX_CHANNELS 3

/*
 Which numeric fields of a [`SeizaFrameSignature`] were actually recorded.

 A cleared bit means "not recorded", which is not the same as zero: a camera
 really can be set to gain 0, and a frame that does not say what gain it used
 is a different thing from one that says zero.

 The flags exist so that a zeroed struct — `= {0}`, `calloc`, `memset`, all
 of them ordinary C — means "nothing recorded" rather than "every setting is
 zero". Getting that backwards silently inverts every comparison, so the
 safe reading is the one you get for free.
 */
#define SEIZA_FRAME_HAS_WIDTH (1 << 0)

#define SEIZA_FRAME_HAS_HEIGHT (1 << 1)

#define SEIZA_FRAME_HAS_CHANNELS (1 << 2)

#define SEIZA_FRAME_HAS_BINNING_X (1 << 3)

#define SEIZA_FRAME_HAS_BINNING_Y (1 << 4)

#define SEIZA_FRAME_HAS_GAIN (1 << 5)

#define SEIZA_FRAME_HAS_OFFSET (1 << 6)

#define SEIZA_FRAME_HAS_READOUT_MODE (1 << 7)

#define SEIZA_FRAME_HAS_FOCAL_LENGTH (1 << 8)

#define SEIZA_FRAME_HAS_ROTATION (1 << 9)

#define SEIZA_FRAME_HAS_EXPOSURE (1 << 10)

#define SEIZA_FRAME_HAS_CAMERA_TEMP (1 << 11)

#define SEIZA_FRAME_HAS_CAPTURED_AT (1 << 12)

/*
 Which fields of a [`SeizaMatchTolerances`] the caller set. A cleared bit
 takes the built-in default for that tolerance.

 A zero tolerance is a legitimate ask — "these must be exactly equal" — so
 it cannot double as "unset". The flags keep both expressible, and make a
 zeroed struct mean "every default", which is what a caller who zeroes one
 almost certainly wants.
 */
#define SEIZA_TOLERANCE_HAS_EXPOSURE (1 << 0)

#define SEIZA_TOLERANCE_HAS_DARK_TEMPERATURE (1 << 1)

#define SEIZA_TOLERANCE_HAS_MASTER_TEMPERATURE (1 << 2)

#define SEIZA_TOLERANCE_HAS_ROTATION (1 << 3)

#define SEIZA_TOLERANCE_HAS_FOCAL_LENGTH (1 << 4)

#define SEIZA_TOLERANCE_HAS_FLAT_SESSION (1 << 5)

#define SEIZA_TOLERANCE_HAS_EXPOSURE_FRACTION (1 << 6)

/*
 An opaque fitted background model. Release it with
 [`seiza_background_model_free`]. Its diagnostics string is borrowed and
 remains valid until the model is freed.
 */
typedef struct SeizaBackgroundModel SeizaBackgroundModel;

/*
 An opaque, thread-safe cooperative cancellation flag. Release it with
 [`seiza_cancel_signal_free`] after every operation borrowing it has
 returned.
 */
typedef struct SeizaCancelSignal SeizaCancelSignal;

/*
 An opaque incremental stacker. Release it with
 [`seiza_live_stacker_free`], or consume it with
 [`seiza_live_stacker_finish`].
 */
typedef struct SeizaLiveStacker SeizaLiveStacker;

/*
 An opaque, owned rendered image. C sees only a pointer; release it with
 [`seiza_rendered_image_free`]. Not `repr(C)`: it is only ever handed to C as
 an opaque pointer, so its layout is private (and cbindgen forward-declares
 it).
 */
typedef struct SeizaRenderedImage SeizaRenderedImage;

/*
 An opaque, owned 16-bit rendered image. Its RGBA samples are native-endian
 `u16` values suitable for a high-bit-depth image encoder. C sees only a
 pointer; release it with [`seiza_rendered_image16_free`].
 */
typedef struct SeizaRenderedImage16 SeizaRenderedImage16;

/*
 A compact immutable live-stack result for non-destructive output. It owns
 only the finalized mean, reference headers, scalar frame counts, and the
 small source-path ledger. Release it with
 [`seiza_stack_export_snapshot_free`].
 */
typedef struct SeizaStackExportSnapshot SeizaStackExportSnapshot;

/*
 An immutable owned stack result. Its image and count pointers are borrowed
 until [`seiza_stack_snapshot_free`] is called.
 */
typedef struct SeizaStackSnapshot SeizaStackSnapshot;

typedef void (*SeizaCatalogSetupProgressCallback)(const char*, void*);

/*
 One reading of an accumulator, in the stack's own units. Only ratios
 between readings of the same stack mean anything.
 */
typedef struct {
  /*
   Frames the accumulator had taken when this was measured.
   */
  uint32_t frames;
  /*
   Pixel-scale noise of the integration, averaged across channels.
   */
  double noise;
  /*
   Median sample, averaged across channels.
   */
  double background;
  /*
   How far the brightest one percent sits above the background.
   */
  double signal;
  /*
   `signal / noise` for this one reading. To compare depths, divide one
   signal — normally the deepest measured — by each depth's noise instead:
   the brightest-percent statistic is itself lifted by noise where a stack
   is shallow, so reading each depth against its own signal flatters the
   early frames.
   */
  double snr;
  /*
   How many entries of `channel_noise` are meaningful.
   */
  size_t channel_count;
  /*
   Per-channel noise.
   */
  double channel_noise[SEIZA_SNR_MAX_CHANNELS];
} SeizaSnrSample;

/*
 What a frame was shot with, as far as matching cares.

 Text fields are null when unknown. Numeric fields are read only when their
 `SEIZA_FRAME_HAS_*` bit is set in `known`, so a zeroed struct means nothing
 was recorded — the safe reading, and the one plain `= {0}` gives you. A
 non-finite value also reads as unknown, whatever its bit says.

 Integer-valued settings are carried as doubles so the struct has one shape;
 every value a camera reports is exact in a double.

 To fill one: zero it, assign the fields the frame recorded, and set each
 one's flag — `light.gain = 100;` then
 `light.known |= SEIZA_FRAME_HAS_GAIN;`. Text fields need no flag.

 C++ callers should write `SeizaFrameSignature light{};` rather than
 `= {0}`; the C spelling is correct but warns under
 `-Wmissing-field-initializers`. Both zero the struct, which is what
 "nothing recorded" is.

 A missing value on the *candidate* side disqualifies it and a missing value
 on the *reference* side accepts what it is offered: a light that does not
 record its gain cannot rule anything out, while a calibration frame that
 does not record its gain cannot prove it belongs. Rotation is the exception
 — unknown on either side matches.
 */
typedef struct {
  /*
   Bitwise OR of the `SEIZA_FRAME_HAS_*` flags for the numeric fields
   this frame actually recorded.
   */
  uint32_t known;
  const char *camera;
  const char *telescope;
  const char *bayer_pattern;
  const char *filter;
  double width;
  double height;
  double channels;
  double binning_x;
  double binning_y;
  double gain;
  double offset;
  double readout_mode;
  double focal_length_mm;
  double rotation_deg;
  double exposure_seconds;
  double camera_temp_c;
  double captured_at_unix;
} SeizaFrameSignature;

/*
 How close two readings have to be to count as the same.

 Every field is optional: set a `SEIZA_TOLERANCE_HAS_*` bit to override that
 tolerance, leave it clear to take the default. A zeroed struct therefore
 means "all defaults", and passing a null pointer anywhere one of these is
 accepted means the same. An override that is negative or not a number is
 ignored in favour of the default.

 The defaults are what a rig's own scatter needs rather than what a
 specification promises. [`seiza_match_tolerances_default`] fills one in if
 you want to read or adjust them.
 */
typedef struct {
  /*
   Bitwise OR of the `SEIZA_TOLERANCE_HAS_*` flags this struct overrides.
   */
  uint32_t known;
  /*
   Dark exposure against light exposure: the floor, in seconds. The
   comparison takes whichever of this and `exposure_fraction` is larger.
   */
  double exposure_seconds;
  /*
   Dark exposure against light exposure: the proportional part, as a
   fraction of the longer of the two. Past about a minute this is what
   decides.
   */
  double exposure_fraction;
  /*
   Dark sensor temperature against light sensor temperature, in Celsius.
   */
  double dark_temperature_c;
  /*
   Sensor temperature within one master's input set, in Celsius.
   */
  double master_temperature_c;
  /*
   Rotator angle between a flat and what it corrects, in degrees.
   */
  double rotation_deg;
  /*
   Focal length between a flat and what it corrects, in millimetres.
   */
  double focal_length_mm;
  /*
   How far apart flats in one master may have been shot, in seconds.
   */
  uint64_t flat_session_seconds;
} SeizaMatchTolerances;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

const char *seiza_core_version(void);

/*
 Applies damped Richardson-Lucy deconvolution to interleaved linear `float`
 samples in place. `channels` must be one or three and `data_length` must
 equal `width * height * channels`. RGB samples are pixel-interleaved.
 The operation is synchronous, retains no pointer after returning, and leaves
 the input unchanged when validation or restoration fails.

 # Safety
 `data` must point to `data_length` writable floats. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
bool seiza_deconvolve_in_place(float *data,
                               size_t data_length,
                               size_t width,
                               size_t height,
                               size_t channels,
                               float psf_fwhm_pixels,
                               size_t iterations,
                               float amount,
                               float noise_fraction,
                               float max_correction,
                               char **error_out);

/*
 Reports the region a color crop would keep across aligned channels, and
 what each channel covers of the shared grid.

 A pixel counts as covered when every sample of every channel there is
 finite, so the reported region is the inner area common to all of them.
 `crop` selects `none`, `bounds`, or `inscribed`; `bounds` keeps the box the
 covered pixels span, and `inscribed` the largest rectangle every channel
 covers in full. The report also names any channel whose coverage sits far
 enough from the others to look like a pointing error rather than dither.

 `names` and `channels` are parallel arrays of `channel_count` entries. Every
 channel holds `data_length` interleaved linear floats on the same
 `width` by `height` grid, with `samples_per_pixel` of one or three. The call
 is synchronous and retains no pointer. The returned JSON is owned by the
 caller and must be released with [`seiza_string_free`].

 # Safety
 `names` must point to `channel_count` NUL-terminated strings and `channels`
 to `channel_count` arrays of `data_length` readable floats. `crop` must be
 NUL-terminated. When non-null, `error_out` must point to writable storage
 for one pointer.
 */
char *seiza_color_crop_report_json(const char *const *names,
                                   const float *const *channels,
                                   size_t channel_count,
                                   size_t data_length,
                                   size_t width,
                                   size_t height,
                                   size_t samples_per_pixel,
                                   const char *crop,
                                   char **error_out);

/*
 Fits a compact background model to interleaved linear `float` samples.

 `channels` must be one or three and `data_length` must equal
 `width * height * channels`. RGB samples are pixel-interleaved. Pass null
 `mask` with zero `mask_length` for automatic fitting, or `width * height`
 bytes where `1` excludes a pixel. The fitted model owns its compact data and
 does not borrow either input buffer after this call returns.
 Pass null or empty `config_json` for `BackgroundConfig::default()`; otherwise
 provide a serialized `seiza-background` `BackgroundConfig`.

 # Safety
 `data` must point to `data_length` readable floats. A non-null `mask` must
 point to `mask_length` readable bytes containing only zero or one. A
 non-null `config_json` must be NUL-terminated. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaBackgroundModel *seiza_background_fit(const float *data,
                                           size_t data_length,
                                           size_t width,
                                           size_t height,
                                           size_t channels,
                                           const uint8_t *mask,
                                           size_t mask_length,
                                           const char *config_json,
                                           char **error_out);

/*
 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
size_t seiza_background_model_width(const SeizaBackgroundModel *model);

/*
 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
size_t seiza_background_model_height(const SeizaBackgroundModel *model);

/*
 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
size_t seiza_background_model_channels(const SeizaBackgroundModel *model);

/*
 Returns the number of floats required by render and correction buffers.

 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
size_t seiza_background_model_data_length(const SeizaBackgroundModel *model);

/*
 Returns borrowed fitted coefficients, references, samples, and diagnostics
 as JSON. The string remains valid until the model is freed.

 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`].
 */
const char *seiza_background_model_diagnostics_json(const SeizaBackgroundModel *model);

/*
 Renders a fitted background into a caller-owned interleaved float buffer.

 # Safety
 `model` must be null or a live pointer returned by [`seiza_background_fit`];
 a null model returns an error. `output` must point to `output_length`
 writable floats. When non-null, `error_out` must point to writable storage
 for one pointer.
 */
bool seiza_background_model_render(const SeizaBackgroundModel *model,
                                   float *output,
                                   size_t output_length,
                                   char **error_out);

/*
 Corrects an interleaved linear float buffer in place. Use
 `SEIZA_BACKGROUND_CORRECTION_SUBTRACT` for additive subtraction or
 `SEIZA_BACKGROUND_CORRECTION_DIVIDE` for multiplicative division.

 # Safety
 `model` must be a live pointer returned by [`seiza_background_fit`]. `data`
 must point to `data_length` writable floats. When non-null, `error_out` must
 point to writable storage for one pointer.
 */
bool seiza_background_model_correct_in_place(const SeizaBackgroundModel *model,
                                             float *data,
                                             size_t data_length,
                                             uint32_t mode,
                                             char **error_out);

/*
 Corrects an interleaved linear float buffer in place with a fractional
 strength. Zero leaves the image unchanged; one applies the full correction.

 # Safety
 `model` must be a live pointer returned by [`seiza_background_fit`]. `data`
 must point to `data_length` writable floats. When non-null, `error_out` must
 point to writable storage for one pointer.
 */
bool seiza_background_model_correct_in_place_with_strength(const SeizaBackgroundModel *model,
                                                           float *data,
                                                           size_t data_length,
                                                           uint32_t mode,
                                                           double strength,
                                                           char **error_out);

/*
 # Safety
 `model` must be null or a pointer returned by [`seiza_background_fit`] that
 has not already been freed.
 */
void seiza_background_model_free(SeizaBackgroundModel *model);

/*
 Create a thread-safe cooperative cancellation flag. The returned owner is
 initially clear and must be released with [`seiza_cancel_signal_free`].
 */
SeizaCancelSignal *seiza_cancel_signal_create(void);

/*
 Ask work borrowing this signal to stop. The call is thread-safe and may be
 made from a UI thread while a worker is inside a cancellable operation.

 # Safety
 `signal` must be null or a live pointer returned by
 [`seiza_cancel_signal_create`]. It must not be freed concurrently.
 */
void seiza_cancel_signal_cancel(const SeizaCancelSignal *signal);

/*
 # Safety
 `signal` must be null or a pointer returned by
 [`seiza_cancel_signal_create`] that has not already been freed. Do not free
 it until every operation borrowing it has returned.
 */
void seiza_cancel_signal_free(SeizaCancelSignal *signal);

/*
 Creates an incremental stack from a copied linear mono or interleaved RGB
 reference frame. Array frames are assumed to be calibrated and debayered.
 Pass null or empty `options_json` for `StackOptions::default()`.

 # Safety
 `reference` must point to `reference_length` readable floats. A non-null
 `options_json` must be NUL-terminated. When non-null, `error_out` must point
 to writable storage for one pointer.
 */
SeizaLiveStacker *seiza_live_stacker_create(const float *reference,
                                            size_t reference_length,
                                            size_t width,
                                            size_t height,
                                            size_t channels,
                                            const char *options_json,
                                            char **error_out);

/*
 Opens a FITS or XISF reference and optional integrated bias, dark, and flat
 masters. A positive `dark_exposure_seconds` overrides the dark metadata; zero
 uses the metadata. Pass null or empty `options_json` for defaults. All files
 are fully read during this call and are not kept open afterward.

 # Safety
 `reference_path` must be a valid NUL-terminated string. Optional paths and
 `options_json` may be null; when non-null they must be NUL-terminated. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
SeizaLiveStacker *seiza_live_stacker_open_fits(const char *reference_path,
                                               const char *bias_path,
                                               const char *dark_path,
                                               const char *flat_path,
                                               double dark_exposure_seconds,
                                               const char *options_json,
                                               char **error_out);

/*
 Reopens a versioned live-stack context previously written by
 [`seiza_live_stacker_save_context`]. The restored handle retains its
 original registration reference, calibration, online rejection moments,
 frame counters, and source-path ledger, and may immediately accept more
 frames.

 # Safety
 `context_path` must be a valid NUL-terminated path. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaLiveStacker *seiza_live_stacker_open_context(const char *context_path, char **error_out);

/*
 Atomically checkpoints every piece of state required to reopen this live
 stack and continue integrating with identical online rejection behavior.
 The live handle remains usable after the checkpoint completes.

 # Safety
 `stacker` must be a live `SeizaLiveStacker` pointer. `context_path` must be
 a valid NUL-terminated path. When non-null, `error_out` must point to
 writable storage for one pointer.
 */
bool seiza_live_stacker_save_context(const SeizaLiveStacker *stacker,
                                     const char *context_path,
                                     char **error_out);

/*
 Returns an owned JSON snapshot of the live stack's resumable identity and
 counters. Free it with [`seiza_string_free`].

 `inputPaths` is the native, ordered source/calibration ledger used for
 duplicate-input and output protection. `configurationFingerprint` is a
 lowercase SHA-256 identity of stack options, current calibration content,
 and input mode; it excludes counters and paths, changes when calibration
 changes, and survives a context round trip.

 # Safety
 `stacker` must be a live `SeizaLiveStacker` pointer. When non-null,
 `error_out` must point to writable storage for one pointer. Externally
 synchronize this read with every mutable operation on the same stacker.
 */
char *seiza_live_stacker_state_json(const SeizaLiveStacker *stacker, char **error_out);

/*
 Load and atomically replace the masters used by later FITS/XISF pushes.

 Each master path is optional. Passing all null/empty paths clears the
 calibration set. A positive `dark_exposure_seconds` overrides the dark
 header; zero uses the header and requires no override. All supplied files
 are fully decoded and the complete set is validated against the immutable
 registration reference before either active calibration or the input-path
 ledger changes. Already integrated frames are not recalibrated. A stack
 created from prepared arrays refuses this operation.

 # Safety
 `stacker` must be a live `SeizaLiveStacker` pointer. Non-null paths must be
 valid NUL-terminated strings. When non-null, `error_out` must point to
 writable storage for one pointer.
 */
bool seiza_live_stacker_set_calibration_fits(SeizaLiveStacker *stacker,
                                             const char *bias_path,
                                             const char *dark_path,
                                             const char *flat_path,
                                             double dark_exposure_seconds,
                                             char **error_out);

/*
 Render a bounded RGBA8 preview directly from the current live mean.

 `config_json` accepts the same stretch / optional background / optional
 deconvolution / optional `sample_domain` schema as
 [`seiza_rendered_image_open_with_stretch_config`]. Physical-domain mapping
 is presentation-only and runs after physical background correction and
 deconvolution, immediately before stretch. When omitted, file-backed
 calibrate-and-prepare stacks use linked robust physical normalization;
 prepared-array stacks retain the legacy unit-linear interpretation.
 `max_dimension` must be positive and bounds the linear buffer before that
 processing. The returned image owns its pixels and remains valid after the
 stack changes; free it with [`seiza_rendered_image_free`].

 # Safety
 `stacker` must be a live `SeizaLiveStacker` pointer and `config_json` a
 valid NUL-terminated string. When non-null, `error_out` must point to
 writable storage for one pointer. Externally synchronize this read with
 every mutable operation on the same stacker.
 */
SeizaRenderedImage *seiza_live_stacker_render_preview(const SeizaLiveStacker *stacker,
                                                      const char *config_json,
                                                      uint32_t max_dimension,
                                                      char **error_out);

/*
 Registers and offers one copied, calibrated linear frame to the stack.
 Returns owned disposition JSON for both accepted and rejected frames; free
 it with [`seiza_string_free`]. A rejected frame is a successful call and is
 represented by `accepted: false` rather than `error_out`.

 # Safety
 `stacker` must be a live pointer returned by a `seiza_live_stacker_*`
 constructor. `frame` must point to `frame_length` readable floats. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
char *seiza_live_stacker_push_linear_json(SeizaLiveStacker *stacker,
                                          const float *frame,
                                          size_t frame_length,
                                          size_t width,
                                          size_t height,
                                          size_t channels,
                                          char **error_out);

/*
 Opens, calibrates, registers, and offers one FITS or XISF frame to the stack.
 Stacks created from an array reject this path, including after a context
 restore. The returned disposition JSON is owned and must be freed with
 [`seiza_string_free`]. Each source path may be offered only once.

 # Safety
 `stacker` must be a live pointer returned by a `seiza_live_stacker_*`
 constructor. `path` must be a valid NUL-terminated string. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
char *seiza_live_stacker_push_fits_json(SeizaLiveStacker *stacker,
                                        const char *path,
                                        char **error_out);

/*
 Offer many FITS or XISF paths at once, preparing several frames in
 parallel. Returns owned JSON that the caller frees with
 [`seiza_string_free`].

 Reads, calibration, registration and normalization overlap across frames
 while integration stays in the order given, so the result is identical to
 offering the same paths one at a time. `paths_json` is a JSON array of
 strings. `workers` is the read concurrency as well as the compute
 concurrency; pass 0 to derive it, or raise it when the frames are remote.
 `max_in_flight_bytes` bounds the memory a derived count may use; pass 0 for
 the default. `normalized_full_scale` puts a frame the file declares as
 normalized (`bounds="0:1"`, as PixInsight writes) onto that scale as it is
 read — pass 65535.0 when the other frames are 16-bit camera data, or 0 to
 leave every sample exactly as stored.

 A path that cannot be read, or that repeats one already stacked, appears in
 the `frames` array with `accepted` false and a `reason`, and the run carries
 on. Check `failed` rather than assuming an absent error means every frame
 landed. There is no cancellation here: a C caller wanting that should offer
 paths in batches.

 # Safety
 `stacker` must be a live pointer returned by a `seiza_live_stacker_*`
 constructor. `paths_json` must be a valid NUL-terminated string. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
char *seiza_live_stacker_push_fits_pipelined_json(SeizaLiveStacker *stacker,
                                                  const char *paths_json,
                                                  size_t workers,
                                                  size_t max_in_flight_bytes,
                                                  float normalized_full_scale,
                                                  char **error_out);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
size_t seiza_live_stacker_width(const SeizaLiveStacker *stacker);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
size_t seiza_live_stacker_height(const SeizaLiveStacker *stacker);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
size_t seiza_live_stacker_channels(const SeizaLiveStacker *stacker);

/*
 Returns the sample count for every live-view and snapshot buffer.

 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
size_t seiza_live_stacker_data_length(const SeizaLiveStacker *stacker);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
uint32_t seiza_live_stacker_accepted_frames(const SeizaLiveStacker *stacker);

/*
 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
uint32_t seiza_live_stacker_rejected_frames(const SeizaLiveStacker *stacker);

/*
 Borrows the current interleaved linear mean without copying it. Zero-
 coverage samples are undefined. The pointer remains valid only until the
 next mutable stacker operation or the stacker is freed/finished.

 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
const float *seiza_live_stacker_mean(const SeizaLiveStacker *stacker);

/*
 Borrows the accepted-observation count for each image sample. The pointer
 has the same lifetime as [`seiza_live_stacker_mean`].

 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
const uint32_t *seiza_live_stacker_coverage(const SeizaLiveStacker *stacker);

/*
 Borrows the rejected-observation count for each image sample. The pointer
 has the same lifetime as [`seiza_live_stacker_mean`].

 # Safety
 `stacker` must be null or a live `SeizaLiveStacker` pointer.
 */
const uint32_t *seiza_live_stacker_rejected_samples(const SeizaLiveStacker *stacker);

/*
 Copies the current mean, variance, coverage, and rejection maps into an
 immutable owned snapshot. Prefer the borrowed live view for display-only
 updates and [`seiza_live_stacker_finish`] for copy-free finalization.

 # Safety
 `stacker` must be a live `SeizaLiveStacker` pointer. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaStackSnapshot *seiza_live_stacker_snapshot(const SeizaLiveStacker *stacker, char **error_out);

/*
 Copies only the finalized mean and scalar frame counts into an immutable
 export owner. Unlike [`seiza_live_stacker_snapshot`], this does not clone
 variance, per-sample coverage, or per-sample rejection maps.

 The returned owner is independent of `stacker`: after this call returns it
 may be transferred to a worker thread, written, and freed without holding
 the live stacker's synchronization lock while ingestion continues.

 # Safety
 `stacker` must be a live `SeizaLiveStacker` pointer. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaStackExportSnapshot *seiza_live_stacker_export_snapshot(const SeizaLiveStacker *stacker,
                                                             char **error_out);

/*
 Consumes a live stacker and moves its full-frame state into an immutable
 snapshot without cloning it. Once a non-null live handle is accepted,
 `*stacker` is set to null and consumed even if finalization reports an
 error.

 # Safety
 `stacker` must point to writable storage containing null or a live pointer
 returned by a `seiza_live_stacker_*` constructor. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaStackSnapshot *seiza_live_stacker_finish(SeizaLiveStacker **stacker, char **error_out);

/*
 # Safety
 `stacker` must be null or a live pointer returned by a
 `seiza_live_stacker_*` constructor and must not already be finished/freed.
 */
void seiza_live_stacker_free(SeizaLiveStacker *stacker);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
size_t seiza_stack_snapshot_width(const SeizaStackSnapshot *snapshot);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
size_t seiza_stack_snapshot_height(const SeizaStackSnapshot *snapshot);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
size_t seiza_stack_snapshot_channels(const SeizaStackSnapshot *snapshot);

/*
 Returns the sample count for every snapshot buffer.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
size_t seiza_stack_snapshot_data_length(const SeizaStackSnapshot *snapshot);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
uint32_t seiza_stack_snapshot_accepted_frames(const SeizaStackSnapshot *snapshot);

/*
 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
uint32_t seiza_stack_snapshot_rejected_frames(const SeizaStackSnapshot *snapshot);

/*
 Borrows the immutable interleaved linear mean until the snapshot is freed.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
const float *seiza_stack_snapshot_image(const SeizaStackSnapshot *snapshot);

/*
 Borrows the immutable per-sample variance until the snapshot is freed.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
const float *seiza_stack_snapshot_variance(const SeizaStackSnapshot *snapshot);

/*
 Borrows the immutable per-sample accepted count until the snapshot is freed.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
const uint32_t *seiza_stack_snapshot_coverage(const SeizaStackSnapshot *snapshot);

/*
 Borrows the immutable per-sample rejection count until the snapshot is
 freed.

 # Safety
 `snapshot` must be null or a live `SeizaStackSnapshot` pointer.
 */
const uint32_t *seiza_stack_snapshot_rejected_samples(const SeizaStackSnapshot *snapshot);

/*
 Writes the immutable stack as an unstretched 32-bit floating-point FITS,
 preserving compatible reference headers.

 # Safety
 `snapshot` must be a live `SeizaStackSnapshot` pointer. `path` must be a
 valid NUL-terminated string. When non-null, `error_out` must point to
 writable storage for one pointer.
 */
bool seiza_stack_snapshot_write_fits(const SeizaStackSnapshot *snapshot,
                                     const char *path,
                                     char **error_out);

/*
 # Safety
 `snapshot` must be null or a live pointer returned by a snapshot/finalize
 function and must not already be freed.
 */
void seiza_stack_snapshot_free(SeizaStackSnapshot *snapshot);

/*
 Writes a compact immutable export snapshot as an unstretched 32-bit
 floating-point FITS, preserving compatible reference headers. The same
 extension-based XISF behavior as [`seiza_stack_snapshot_write_fits`] is
 retained.

 This call reads only the export owner and may run on a worker thread after
 [`seiza_live_stacker_export_snapshot`] returns; the live stacker is no
 longer involved.

 # Safety
 `snapshot` must be a live `SeizaStackExportSnapshot` pointer. `path` must
 be a valid NUL-terminated string. When non-null, `error_out` must point to
 writable storage for one pointer. Do not free `snapshot` until this call
 returns.
 */
bool seiza_stack_export_snapshot_write_fits(const SeizaStackExportSnapshot *snapshot,
                                            const char *path,
                                            char **error_out);

/*
 # Safety
 `snapshot` must be null or a live pointer returned by
 [`seiza_live_stacker_export_snapshot`] and must not already be freed.
 */
void seiza_stack_export_snapshot_free(SeizaStackExportSnapshot *snapshot);

/*
 Returns catalog readiness and resolved component paths as JSON.

 # Safety
 `catalog_directory` may be null or a valid NUL-terminated string. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
char *seiza_catalog_status_json(const char *catalog_directory, char **error_out);

/*
 Downloads and installs a solver-ready Seiza catalog preset.

 Preset `0` is the standard G≤17 blind-solving package, `1` is the optional
 G≤20 package, and `2` installs every published catalog. The call is
 synchronous and must run off the UI thread. Progress JSON is valid only for
 the duration of each callback.

 This builds its own blocking Tokio runtime for the download, so it must not
 be called from a thread already inside an async runtime; doing so panics,
 which this call catches and returns through `error_out`.

 # Safety
 `catalog_directory` may be null or a valid NUL-terminated string. `context`
 is passed through untouched to `progress`. When non-null, `error_out` must
 point to writable storage for one pointer.
 */
bool seiza_catalog_setup(const char *catalog_directory,
                         uint32_t preset,
                         SeizaCatalogSetupProgressCallback progress,
                         void *context,
                         char **error_out);

/*
 Opens and renders an image for the C ABI.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open(const char *path,
                                              double target_median,
                                              double shadows_clip,
                                              uint32_t max_dimension,
                                              char **error_out);

/*
 Opens and renders an image with an explicit RGB stretch mode.

 Mode `0` is per-channel auto, `1` is linked auto, and `2` is linear.
 Non-RGB FITS/XISF and standard raster images ignore this setting.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open_with_rgb_stretch(const char *path,
                                                               double target_median,
                                                               double shadows_clip,
                                                               uint32_t max_dimension,
                                                               uint32_t rgb_stretch_mode,
                                                               char **error_out);

/*
 Opens a FITS or XISF image and renders it with parameterized processing described by
 `config_json`. The value may be one serialized `seiza-stretch`
 `StretchConfig` (the original schema), a non-empty array of configs, or an
 object with `stretch`, optional `background`, optional `deconvolution`,
 optional `sample_domain`, and optional `interactive_preview` fields. Array
 stages are applied in order using `f32` intermediates and converted to RGBA
 only after the final stage. Background correction and deconvolution, when
 requested, are applied to linear samples in that order. Sample-domain
 mapping then converts physical values to the unit-linear domain expected by
 stretch, without changing the source image or scientific outputs. Omitting
 it retains the legacy unit-linear interpretation for file renders.
 Interactive preview mode bounds the linear samples to `max_dimension`
 before processing and reuses the source/background-prepared pixels across
 stretch, domain, and deconvolution edits; full renders should leave it
 false. Metadata reports both the requested and resolved sample domain.

 # Safety
 `path` and `config_json` must be valid NUL-terminated strings. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaRenderedImage *seiza_rendered_image_open_with_stretch_config(const char *path,
                                                                  const char *config_json,
                                                                  uint32_t max_dimension,
                                                                  char **error_out);

/*
 Opens and renders an image to native-endian RGBA16 for high-bit-depth
 export. This is a separate allocation from the RGBA8 preview API, so normal
 preview renders do not pay the memory cost of both pixel formats.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage16 *seiza_rendered_image16_open(const char *path,
                                                  double target_median,
                                                  double shadows_clip,
                                                  uint32_t max_dimension,
                                                  char **error_out);

/*
 Opens and renders an image to native-endian RGBA16 with an explicit RGB
 stretch mode. Mode `0` is per-channel auto, `1` is linked auto, and `2` is
 linear. Non-RGB FITS/XISF and standard raster images ignore this setting.

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
SeizaRenderedImage16 *seiza_rendered_image16_open_with_rgb_stretch(const char *path,
                                                                   double target_median,
                                                                   double shadows_clip,
                                                                   uint32_t max_dimension,
                                                                   uint32_t rgb_stretch_mode,
                                                                   char **error_out);

/*
 Opens a FITS or XISF image and renders its parameterized processing stack to
 native-endian RGBA16. The JSON schema and processing order are identical to
 [`seiza_rendered_image_open_with_stretch_config`], but the final stretch is
 quantized directly from `f32` to `u16` instead of passing through RGBA8.

 # Safety
 `path` and `config_json` must be valid NUL-terminated strings. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
SeizaRenderedImage16 *seiza_rendered_image16_open_with_stretch_config(const char *path,
                                                                      const char *config_json,
                                                                      uint32_t max_dimension,
                                                                      char **error_out);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
uint32_t seiza_rendered_image_width(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
uint32_t seiza_rendered_image_height(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`]. The returned buffer is valid until the image
 is freed.
 */
const uint8_t *seiza_rendered_image_rgba(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
size_t seiza_rendered_image_rgba_length(const SeizaRenderedImage *image);

/*
 Returns the image as BGRA8 (Direct2D / WinUI byte order), computed from the
 canonical RGBA on first use and cached. The returned buffer is valid until
 the image is freed.

 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
const uint8_t *seiza_rendered_image_bgra(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`].
 */
size_t seiza_rendered_image_bgra_length(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by
 [`seiza_rendered_image_open`]. The returned string is valid until the image
 is freed.
 */
const char *seiza_rendered_image_metadata_json(const SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a pointer returned by [`seiza_rendered_image_open`]
 that has not already been freed.
 */
void seiza_rendered_image_free(SeizaRenderedImage *image);

/*
 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
uint32_t seiza_rendered_image16_width(const SeizaRenderedImage16 *image);

/*
 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
uint32_t seiza_rendered_image16_height(const SeizaRenderedImage16 *image);

/*
 Returns borrowed native-endian RGBA16 samples. The returned buffer remains
 valid until the image is freed.

 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
const uint16_t *seiza_rendered_image16_rgba(const SeizaRenderedImage16 *image);

/*
 Returns the RGBA16 buffer length in `uint16_t` elements, not bytes.

 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
size_t seiza_rendered_image16_rgba_length(const SeizaRenderedImage16 *image);

/*
 Returns borrowed render metadata JSON. The string remains valid until the
 image is freed.

 # Safety
 `image` must be null or a live pointer returned by a
 `seiza_rendered_image16_open*` function.
 */
const char *seiza_rendered_image16_metadata_json(const SeizaRenderedImage16 *image);

/*
 # Safety
 `image` must be null or a pointer returned by a
 `seiza_rendered_image16_open*` function that has not already been freed.
 */
void seiza_rendered_image16_free(SeizaRenderedImage16 *image);

/*
 Solves an image and returns a JSON string for the C ABI.

 # Safety
 `path` must be a valid NUL-terminated string. `catalog_directory` may be
 null or a valid NUL-terminated string. When non-null, `error_out` must point
 to writable storage for one pointer.
 */
char *seiza_solve_image_json(const char *path,
                             const char *catalog_directory,
                             double minimum_scale_arcsec_per_pixel,
                             double maximum_scale_arcsec_per_pixel,
                             uint8_t sip_order,
                             char **error_out);

/*
 # Safety
 `value` must be null or a string returned by this library that has not
 already been freed.
 */
void seiza_string_free(char *value);

/*
 Read only a FITS/XISF header and return normalized frame-role, calibration
 state, and matching-signature JSON. No pixel payload is decoded. The owned
 string must be released with [`seiza_string_free`].

 # Safety
 `path` must be a valid NUL-terminated string. When non-null, `error_out`
 must point to writable storage for one pointer.
 */
char *seiza_probe_frame_json(const char *path, char **error_out);

/*
 Select a proximity-ordered, internally coherent set of calibration-frame
 probe records without duplicating Seiza's matching policy in a host.

 `request_json` contains `kind` (`bias`, `dark`, `dark-flat`, or `flat`), a
 `reference` record, `candidates`, optional `minimum` (default 2), and
 optional camelCase tolerances. Dark flats use dark exposure/temperature
 matching and should reference the selected flat they will calibrate. Each
 record has `path`, `role`, and the `signature` object returned by
 [`seiza_probe_frame_json`]; extra probe fields are ignored.
 The owned response reports `matchedPaths`, coherent `selectedPaths`,
 `ready`, and one stable exclusion reason per omitted candidate. Free it
 with [`seiza_string_free`].

 # Safety
 `request_json` must be a valid NUL-terminated string. When non-null,
 `error_out` must point to writable storage for one pointer.
 */
char *seiza_calibration_plan_json(const char *request_json, char **error_out);

/*
 Build and atomically publish one calibration master from raw FITS/XISF
 paths, returning an owned JSON integration report.

 The camelCase request has `kind`, at least two `inputs`, and `output`;
 optional fields are `bias`, `dark`, `darkExposureSeconds`,
 `exposureSeconds`, `rejection` (`lowSigma`, `highSigma`), and
 `defectSuppression` (`lowSigma`, `highSigma`). `dark` is a dark-flat when
 building a flat. Defect suppression is accepted only for flats, because a
 dark master must retain the hot pixels it is meant to subtract.

 Construction is a two-pass leave-one-out sigma-clipped mean and may take
 minutes. Run it off the UI thread. `cancel` may be null; otherwise another
 thread may call [`seiza_cancel_signal_cancel`]. Cancellation is checked
 between input frames, returns failure through `error_out`, and publishes no
 output. FITS/XISF writers publish through a same-directory temporary file,
 so every successful output is atomic. Free the response with
 [`seiza_string_free`].

 Response schema 2 reports `requestedFrames`, accepted `inputFrames` and
 accepted-only per-frame `inputs`, plus `skippedInputs` entries with `path`
 and `reason` for metadata disagreements the integrator set aside. The
 accepted and skipped paths are disjoint and account for every requested
 input in request order.

 # Safety
 `request_json` must be a valid NUL-terminated string. `cancel` must be null
 or a live [`SeizaCancelSignal`] retained until this call returns. When
 non-null, `error_out` must point to writable storage for one pointer.
 */
char *seiza_calibration_build_master_json(const char *request_json,
                                          const SeizaCancelSignal *cancel,
                                          char **error_out);

/*
 Read how deep a live stack is, without copying the accumulator.

 Returns 1 and fills `sample` when the stack could be measured, 0 when it
 could not — too small a frame, or too little of it covered, which is an
 ordinary answer early in a build rather than an error — and -1 on failure,
 with `error_out` set.

 **Test the return against 1, not for truth.** -1 is non-zero, so
 `if (seiza_live_stacker_measure_depth(...))` is true on failure. `sample`
 is cleared to zero on entry and only carries a reading when the return is
 exactly 1.

 # Safety

 `stacker` must be a live `SeizaLiveStacker` pointer and `sample` must point
 at writable storage for one `SeizaSnrSample`.
 */
int32_t seiza_live_stacker_measure_depth(const SeizaLiveStacker *stacker,
                                         SeizaSnrSample *sample,
                                         char **error_out);

/*
 The depths a build of `total` frames should measure at: the doubling
 ladder, and the full set.

 Writes up to `out_len` depths into `out` and returns how many the ladder
 has in total, which may exceed `out_len`. Pass a null `out` with a zero
 `out_len` to ask for the count alone.

 # Safety

 `out` must point at writable storage for `out_len` values, or be null when
 `out_len` is zero.
 */
size_t seiza_checkpoint_depths(size_t total, size_t *out, size_t out_len);

/*
 Fill a signature with "nothing recorded". Equivalent to zeroing it, and
 offered so callers in languages without designated initializers have a
 spelling.

 # Safety

 `signature` must point at writable storage for one `SeizaFrameSignature`.
 */
void seiza_frame_signature_init(SeizaFrameSignature *signature);

/*
 Whether two frames came off the same sensor in the same mode. Returns 1 for
 a match, 0 for a mismatch, -1 on failure with `error_out` set.

 # Safety

 Both pointers must reference initialized `SeizaFrameSignature` values, with
 any text fields either null or valid UTF-8 C strings.
 */
int32_t seiza_calibration_sensor_matches(const SeizaFrameSignature *reference,
                                         const SeizaFrameSignature *candidate,
                                         char **error_out);

/*
 Fill `tolerances` with the built-in defaults and every flag set, so a
 caller can read them or adjust one and pass the rest through unchanged.

 # Safety

 `tolerances` must point at writable storage for one
 `SeizaMatchTolerances`.
 */
void seiza_match_tolerances_default(SeizaMatchTolerances *tolerances);

/*
 Whether a flat describes the same optical path as what it would correct —
 filter, telescope, focal length and rotator angle. Returns 1, 0, or -1 as
 [`seiza_calibration_sensor_matches`] does.

 `tolerances` may be null for the defaults; see [`SeizaMatchTolerances`].

 # Safety

 As [`seiza_calibration_sensor_matches`]. `tolerances` must be null or
 reference an initialized `SeizaMatchTolerances`.
 */
int32_t seiza_calibration_optics_match(const SeizaFrameSignature *reference,
                                       const SeizaFrameSignature *candidate,
                                       const SeizaMatchTolerances *tolerances,
                                       char **error_out);

/*
 Whether a dark's exposure and sensor temperature suit the frame it would be
 subtracted from. Reads `exposure_seconds` and `camera_temp_c` from both
 signatures. Returns 1, 0, or -1 as
 [`seiza_calibration_sensor_matches`] does.

 `tolerances` may be null for the defaults; see [`SeizaMatchTolerances`].

 # Safety

 As [`seiza_calibration_sensor_matches`]. `tolerances` must be null or
 reference an initialized `SeizaMatchTolerances`.
 */
int32_t seiza_calibration_dark_matches(const SeizaFrameSignature *reference,
                                       const SeizaFrameSignature *candidate,
                                       const SeizaMatchTolerances *tolerances,
                                       char **error_out);

/*
 Whether two rotator angles are close enough to share a flat. Wraps at 360,
 and a non-finite angle on either side matches — a missing angle means the
 rig had no rotator, or the record predates keeping one.

 Takes its tolerance directly rather than a [`SeizaMatchTolerances`], being
 a single comparison with a single tolerance.
 [`seiza_match_tolerances_default`] gives the value the other entry points
 use.
 */
int32_t seiza_calibration_rotation_matches(double reference_deg,
                                           double candidate_deg,
                                           double tolerance_deg);

/*
 Fit the camera pedestal in `light`, in the light's own units.

 Dividing by a flat only works on a signal that starts at zero; without a
 bias or dark master the offset is still there. Sky background varies with
 the flat's own response, so the intercept of that line is the part that
 does not.

 Returns 1 and writes `pedestal` when the fit succeeded, 0 when the frame
 cannot support one — too few usable tiles, a flat too uniform to give the
 line a lever, or a slope saying the model does not describe this field —
 and -1 when the caller passed something unusable, with `error_out` set.

 **Test the return against 1, not for truth.** -1 is non-zero. `pedestal` is
 set to NaN on entry and only carries a fit when the return is exactly 1 —
 zero would be ambiguous, since a camera with no offset fits exactly that.

 The fit reads low by roughly 0.8 times the frame's noise, by construction.
 That is the safe direction, and it cancels when comparing two frames.

 # Safety

 `light` and `flat` must each point at `width * height` readable floats.
 `pedestal` must point at writable storage for one float.
 */
int32_t seiza_calibration_fit_flat_pedestal(const float *light,
                                            const float *flat,
                                            size_t width,
                                            size_t height,
                                            float *pedestal,
                                            char **error_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SEIZA_CABI_H */
